### ISSUE TITLE
FreeBSD: unable to set blendmode

### ISSUE THREAD

**Issue by rmoog** [katajakasa/SDL_kitchensink#24]
This happens on FreeBSD 11.0 on Raspberry Pi B+

**Comment by katajakasa** [comment]
SDL + *BSD problem, this is not the right place to report this since
a) This is a problem in SDL2 port / FreeBSD and ...
b) This is not SDL2 (port) bugtracker
c) I have no *BSD installation and I do not / can not directly support compilation/usage on *BSD.

Please report SDL2 FreeBSD port issues in their bugtracker.
