### ISSUE TITLE
Please let user control if CMake will generate a static library or not

### ISSUE THREAD

**Issue by grepwood** [katajakasa/SDL_kitchensink#60]
I've packaged SDL_kitchensink for Gentoo in https://gitlab.com/src_prepare/src_prepare-overlay and I had to overcome CMake's strange behavior of generating a static library no matter what. This is not needed if a user does not set USE=static, so there's an exception in the ebuild that uses `find` with `-delete` to remove the static library if it is undesired.

**Comment by grepwood** [comment]
Please change label to feature request. This is not a bug :)

**Comment by katajakasa** [comment]
This is technically not cmakes issue, but due to how kitchensink uses cmakes build scripts -- we force both static and shared libraries instead of relying on cmakes internal mechanism for choosing between them. This is used, as the examples link the static library, and because I like to build both when dev-testing :P

Instead of adding switch for building/not building the static library, would it be enough that we build both, but allow static libraries to be left out in installation phase ("make install") ?

**Comment by katajakasa** [comment]
It should now be possible to use "cmake -DBUILD_SHARED=1|0 -DBUILD_STATIC=1|0 ..." to switch shared and static library builds on or off. Examples will use static libs if available, shared if not.

Changes are in master, please test (I will eventually roll out a release) :)

**Comment by katajakasa** [comment]
Released in 1.0.8. Closing this ticket as done, please reopen if needed :)

**Comment by grepwood** [comment]
@katajakasa everything works fine. Thank you!
